version: '3'
services:
  frontend:
    image: ${ECR_REGISTRY}/eventhub-frontend:latest
    ports:
      - "80:3000"
    restart: always

  backend:
    image: ${ECR_REGISTRY}/eventhub-backend:latest
    ports:
      - "5000:8080"
    restart: always
