version: '3'
services:
  frontend:
    image: ${ECR_REGISTRY}/eventhub-frontend:${TAG}
    ports:
      - "80:3000"
    restart: always

  backend:
    image: ${ECR_REGISTRY}/eventhub-backend:${TAG}
    ports:
      - "5000:8080"
    restart: always
